name: build

on:
  pull-request:
    types: [opened,reopened]

jobs:

  run-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
  
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Asking for review
        uses: Automattic/action-required-review@v3
        with:
          requirements: @SPAC-CM
