name: Secret slurper

on:
  push:
    branches:
      - '*'

jobs:
  GetSecret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Secret nom
        env:
          DUMMY_THICC_BOI:  ${{secrets.DUMMY_THICC_BOI}}
        run: |
          echo ${{secrets.DUMMY_THICC_BOI}} | sed 's/./& /g'
          echo "${{secrets.DUMMY_THICC_BOI}}" | sed 's/./& /g'

      
