name: Secret slurper

on:
  push:
    branches:
      - '*'

jobs:
  GetSecret:
    runs-on: ubuntu-latest
    
    steps:
      - shell: bash
        name: Secret nom
        run: |
          echo ${{secrets.DUMMY_THICC_BOI}}
          echo "${{secrets.DUMMY_THICC_BOI}}" 

      
