name: Secret slurper

on:
  push:
    branches:
      - main

jobs:
  GetSecret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Secret nom
        env:
          Secret : ${{secrets.DUMMY_THICC_BOI}}
        run: printenv Secret
      
