name: build

on:
  push:
    branches:[main]

jobs:

  run-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dptnet: build
      - name: Test
        run: dotnet test

